#!/bin/bash
#
# ██╗     ██╗███╗   ███╗███████╗██╗  ██╗ █████╗ ██╗    ██╗██╗  ██╗
# ██║     ██║████╗ ████║██╔════╝██║  ██║██╔══██╗██║    ██║██║ ██╔╝
# ██║     ██║██╔████╔██║█████╗  ███████║███████║██║ █╗ ██║█████╔╝
# ██║     ██║██║╚██╔╝██║██╔══╝  ██╔══██║██╔══██║██║███╗██║██╔═██╗
# ███████╗██║██║ ╚═╝ ██║███████╗██║  ██║██║  ██║╚███╔███╔╝██║  ██╗
# ╚══════╝╚═╝╚═╝     ╚═╝╚══════╝╚═╝  ╚═╝╚═╝  ╚═╝ ╚══╝╚══╝ ╚═╝  ╚═╝
# ================================================================================
#  SCRIPT   : Rustic Backup Runner (Unix)                            v1.0.0
#  AUTHOR   : Limehawk.io
#  DATE     : April 2026
#  USAGE    : sudo ./rustic_backup_unix.sh
# ================================================================================
#  FILE     : rustic_backup_unix.sh
#  DESCRIPTION : Runs rustic backup, prune, and integrity check (Linux/macOS)
# --------------------------------------------------------------------------------
#  README
# --------------------------------------------------------------------------------
#  PURPOSE
#
#    Executes a full Rustic backup cycle on Linux and macOS: runs a backup
#    against the configured repository, applies retention policy with prune,
#    and performs a partial integrity check on the repository. Reads all
#    configuration from /etc/rustic/rustic.toml. Intended to be run on a
#    schedule (systemd timer or launchd plist) or invoked directly via
#    SuperOps RMM.
#
#  DATA SOURCES & PRIORITY
#
#    - /etc/rustic/rustic.toml — all backend, repository, and backup settings
#    - /usr/local/bin/rustic   — rustic binary
#
#  REQUIRED INPUTS
#
#    No runtime variables. All configuration is read from the TOML file
#    generated by rustic_install_unix.sh.
#
#  SETTINGS
#
#    Hardcoded paths:
#      - Binary : /usr/local/bin/rustic
#      - Config : /etc/rustic/rustic.toml
#
#    Integrity check scope: --read-data-subset=1/100 (1% of data per run)
#
#  BEHAVIOR
#
#    The script performs the following actions in order:
#    1. Verifies that the rustic binary and config file exist
#    2. Exports RUSTIC_CONFIG_FILE to direct rustic to the TOML config
#    3. Runs rustic backup — fatal if it fails
#    4. Runs rustic forget --prune (retention policy) — warns if it fails
#    5. Runs rustic check --read-data-subset=1/100 (integrity) — warns if fails
#    6. Reports total duration and exits 0
#
#  PREREQUISITES
#
#    - Linux or macOS
#    - Root privileges (runs as root via RMM)
#    - rustic installed at /usr/local/bin/rustic
#    - /etc/rustic/rustic.toml configured by rustic_install_unix.sh
#    - Network access to the configured backup backend
#
#  SECURITY NOTES
#
#    - No credentials are printed to console output
#    - All secrets remain in the TOML config file (chmod 600)
#
#  EXIT CODES
#
#    0 = Success
#    1 = Failure (binary/config missing, or backup step failed)
#
#  EXAMPLE RUN
#
#    [INFO] RUSTIC BACKUP
#    ==============================================================
#      Binary : /usr/local/bin/rustic
#      Config : /etc/rustic/rustic.toml
#
#    [RUN] BACKUP
#    ==============================================================
#      snapshot abc12345 saved
#
#    [RUN] RETENTION
#    ==============================================================
#      applying retention policy
#      removed 2 snapshots
#
#    [RUN] INTEGRITY CHECK
#    ==============================================================
#      checking repository structure
#      check completed
#
#    [OK] FINAL STATUS
#    ==============================================================
#      Result   : SUCCESS
#      Duration : 42s
#
#    [OK] SCRIPT COMPLETE
#    ==============================================================
#
# --------------------------------------------------------------------------------
#  CHANGELOG
# --------------------------------------------------------------------------------
#  2026-04-04 v1.0.0 Initial release
# ================================================================================

set -euo pipefail

# ==== HARDCODED PATHS ====
RUSTIC_BIN="/usr/local/bin/rustic"
CONFIG_FILE="/etc/rustic/rustic.toml"

# ==== TIMER ====
START_TIME="$(date +%s)"

# ==== PRE-FLIGHT CHECKS ====
if [[ ! -x "${RUSTIC_BIN}" ]]; then
    echo "[ERROR] PREFLIGHT CHECK"
    echo "=============================================================="
    echo "  rustic binary not found or not executable: ${RUSTIC_BIN}"
    echo "  Run rustic_install_unix.sh to install rustic first."
    echo ""
    echo "[ERROR] SCRIPT COMPLETE"
    echo "=============================================================="
    exit 1
fi

if [[ ! -f "${CONFIG_FILE}" ]]; then
    echo "[ERROR] PREFLIGHT CHECK"
    echo "=============================================================="
    echo "  Config file not found: ${CONFIG_FILE}"
    echo "  Run rustic_install_unix.sh to generate the configuration."
    echo ""
    echo "[ERROR] SCRIPT COMPLETE"
    echo "=============================================================="
    exit 1
fi

# ==== EXPORT CONFIG PATH ====
export RUSTIC_CONFIG_FILE="${CONFIG_FILE}"

# ==== INFO ====
echo ""
echo "[INFO] RUSTIC BACKUP"
echo "=============================================================="
echo "  Binary : ${RUSTIC_BIN}"
echo "  Config : ${CONFIG_FILE}"

# ==== BACKUP ====
echo ""
echo "[RUN] BACKUP"
echo "=============================================================="
"${RUSTIC_BIN}" backup 2>&1 | sed 's/^/  /'
# set -e ensures this exits 1 if backup fails

# ==== RETENTION ====
echo ""
echo "[RUN] RETENTION"
echo "=============================================================="
if "${RUSTIC_BIN}" forget --prune 2>&1 | sed 's/^/  /'; then
    echo "  Retention policy applied successfully"
else
    echo ""
    echo "[WARN] RETENTION"
    echo "=============================================================="
    echo "  rustic forget --prune failed — snapshots may not have been pruned"
    echo "  Review output above. Backup data is intact."
fi

# ==== INTEGRITY CHECK ====
echo ""
echo "[RUN] INTEGRITY CHECK"
echo "=============================================================="
if "${RUSTIC_BIN}" check --read-data-subset=1/100 2>&1 | sed 's/^/  /'; then
    echo "  Integrity check passed"
else
    echo ""
    echo "[WARN] INTEGRITY CHECK"
    echo "=============================================================="
    echo "  rustic check failed — repository may have integrity issues"
    echo "  Review output above. Consider running a full check manually."
fi

# ==== DURATION ====
END_TIME="$(date +%s)"
DURATION=$(( END_TIME - START_TIME ))

# ==== FINAL STATUS ====
echo ""
echo "[OK] FINAL STATUS"
echo "=============================================================="
echo "  Result   : SUCCESS"
echo "  Duration : ${DURATION}s"

echo ""
echo "[OK] SCRIPT COMPLETE"
echo "=============================================================="
exit 0
