name: windows_laps_entra_configure.ps1
description: Configures Windows LAPS to back up the local admin password to Entra ID
shell: POWERSHELL
runAs: SYSTEM
timeout: 300
groupId: Z2lkOi8vbGV2ZWwvU2NyaXB0R3JvdXAvNTQ2NDU
scriptId: Z2lkOi8vbGV2ZWwvU2NyaXB0LzEyNzk3MA
lastPushedChecksum: "sha256:70cdd1f031aea21d"
lastPushedMetaChecksum: "sha256:2f3697defacd5999"